### ISSUE TITLE
Symbol’s chain of function indirections contains a loop with Emacs 25.1

### ISSUE THREAD

**Issue by gergelypolonkai** [pmiddend/emacs-rtm#2]
Using Emacs 25.1 I get this error whenever I try to use `helm-M-x` after I `(require 'rtm)`:

```
Symbol’s chain of function indirections contains a loop: def-rtm-authenticated-scalar-method
```

With Emacs 24.5.1 `(require 'rtm)` freezes Emacs (I can get back to work with <kbd>C-g</kbd>).

**Comment by rafaelleru** [comment]
same here

**Comment by jamezpolley** [comment]
I've just added a pull request which seems to fix this for me.

As a workaround until this lands:

 - install the rtm package in the usual way
- find your `rtm.el` file (mine was at `~/.emacs.d/elpa/rtm-20160116.927`
- remove this line by hand and save the file
- `rm rtm.elc` to remove the byte-compiled version
- restart emacs

**Comment by pmiddend** [comment]
I've merged the PR, can this be closed?
